name: Caller Workflow

on:
  push:
    branches:
      - main  # Adjust this as necessary

jobs:
  call_reusable_workflow:
    uses: STDineshKumar/testing/.github/workflows/testing.yml@main
    with:
      input1: "Hello from caller!"
