name: hello
on:
  push:
      branches:
      - 'main'
jobs:
  basic-ubuntu-20:
    runs-on: ubuntu-20.04
    steps:
      - name: helloworld
        run: echo "Hello World"
      - name: Setup Python
        uses: actions/setup-python@v5.2.0
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"        
